### ISSUE TITLE
False Claim

### ISSUE THREAD

**Issue by sfodje** [kak-tus/perltidy-more#1]
@sfodje here:

Just wanted to point out that the claim on your README.md page about my extension being only able to handle 10 to 20 KB is provably false. It's been able to handle a lot larger than that from day one.

However, there was an issue with additionalArguments not working and my github repo not being available which was brought to my attention by a review and I promptly fixed that.

We now have two extensions that do exactly the same thing, but yours makes a false claim about mine and I would like that retracted.

Also every other issue raised has been fixed.

Thanks

**Comment by kak-tus** [comment]
Thank you. Fixed.
