### ISSUE TITLE
Clears file on save

### ISSUE THREAD

**Issue by olefasting** [kak-tus/perltidy-more#2]
Hi!
Was trying out the different perl extensions today, and when trying yours, I noticed that it cleared my perl script on every save.
I guess there is something wrong with the formatting....

**Comment by kak-tus** [comment]
What do you mean with "cleared"? After save you gets empty file?

**Comment by olefasting** [comment]
Yeah, the buffer is cleared, and if I save the change goes to the file as well

**Comment by kak-tus** [comment]
Is there are any other perl formatting extensions enabled at the same time? [This](https://marketplace.visualstudio.com/items?itemName=henriiik.vscode-perl) or [this](https://marketplace.visualstudio.com/items?itemName=sfodje.perltidy)?

If yes, please try do disable them one by one and try to format file.

**Comment by kak-tus** [comment]
Is perltidy installed? :)

What values have plugin configuration options?
```
  // Path to perltidy binary
  "perltidy-more.executable": "perltidy",

  // Path to .perltidyrc file
  "perltidy-more.profile": "",
```

**Comment by olefasting** [comment]
Ok, now I feel stupid. Thought this was a stand alone extension. Sorry for this :p

**Comment by kak-tus** [comment]
:+1:
