### ISSUE TITLE
Perltidy does not run

### ISSUE THREAD

**Issue by kraih** [kak-tus/perltidy-more#3]
I've tested this extension with VS Code 1.14.1, Perl 5.26.0 and Perl::Tidy 20170521, and it appears that it might not be working anymore. Nothing happens when i press the formatter keyboard shortcut. With [the other perltidy extension](https://marketplace.visualstudio.com/items?itemName=sfodje.perltidy) everything seems to work fine.

**Comment by kak-tus** [comment]
I think, than you have enabled both perl formatting extensions at same time.

Please, try:
1. Upgrade this extension to 0.4 (published just now).
2. Use F1 or Ctrl+Shift+P and "perltidy" command - this will formating code.
3. If 2 works as expected - another extension redefined "formatting" shortcut (both extensions was register formatter and VS Code selected one of them).

**Comment by kraih** [comment]
No, i didn't have both installed, there were two other problems. First was the same problem i've [reported for the other perltidy extension](https://github.com/sfodje/perltidy/issues/1). And the second was that i had the [Mojolicious extension](https://github.com/kraih/vscode-mojo) installed, which changes the syntax to `Perl (Mojolicious)`, which makes the formatter shortcut not work anymore. Using the `perltidy` command does work.

**Comment by kraih** [comment]
Btw. I've also tried to assign a shortcut to `perltidy-more.tidy`, but that doesn't seem to work with `Perl (Mojolicious)`. Only `ctrl+shift+p` and `perltidy` does when the syntax is not `Perl`.

**Comment by kraih** [comment]
Removed the comment about the custom shortcut for `perltidy-more.tidy`, it works fine now. I must have made a typo or so.

**Comment by kraih** [comment]
In case someone else stumbles over this, a `{"key": "alt+p", "command": "perltidy-more.tidy"}` shortcut solves the multi Perl syntax problem nicely.

**Comment by kraih** [comment]
That only leaves the problem with `"perltidy.profile": ".../.perltidyrc"` resulting in background perl processes that run forever and keep a CPU core busy.

**Comment by kak-tus** [comment]
Try
1. perltidy-more.profile
2. Absolute path.

**Comment by kak-tus** [comment]
With this ".../.perltidyrc" you want to use specific profile for each project?

**Comment by kraih** [comment]
Absolute path works. `.../.perltidyrc` is a special value though, it tells `perltidy` to search for a `.perltidyrc` file in the parent directories, so you can have different files for each project and they just work.

**Comment by kak-tus** [comment]
ok, I understand. Fix it shortly.

**Comment by kak-tus** [comment]
And also will add "Perl (Mojolicious)" type.

**Comment by kak-tus** [comment]
Done, tested, works fine in my case. Please, try it.

**Comment by kraih** [comment]
Works perfectly for me, thanks! 👍
