### ISSUE TITLE
First search for .perltidy in the project root

### ISSUE THREAD

**Issue by akarelas** [kak-tus/perltidy-more#4]
I believe that right now this plugin only uses the .perltidyrc that exists in $HOME

I would like this plugin to first use the .perltidyrc that exists in the project root directory.

**Comment by kak-tus** [comment]
Use "perltidy-more.profile" option and set it to ".../.perltidyrc". Three dots is perltidy specific option to indicates that the file should be searched for starting in the current directory and working upwards. This makes it easier to have multiple projects each with their own .perltidyrc in their root directories.

**Comment by akarelas** [comment]
Can you please write this tip in the plugin page? Everybody must know this, but I think very few people know it. Thanks!

**Comment by kak-tus** [comment]
I've done it here :)
https://github.com/kak-tus/perltidy-more/commit/2fe58af1931fd1f1a0124dd981ead74f5b0e9c29

In readme and in configuration page
![image](https://user-images.githubusercontent.com/3152421/48092643-4b003080-e21e-11e8-982f-134558fc2441.png)
