### ISSUE TITLE
Fails Formatting on Virtual Workspaces

### ISSUE THREAD

**Issue by j-ecko** [kak-tus/perltidy-more#5]
I really like being able to use Tidy from within VS Code - it's a real time saver.

I did bump in to an issue, though:

When using workspaces that are provided by remote file system providers like SSH FS (v1.11.2), the tidy spawn() fails because it is given the current working directory of the document being Tidy'd - which doesn't actually exist on the local machine.

Since the extension does everything with stdin/stdout, spoof'ing the CWD setting for the spawn() with something like the following:

       let options = {
            cwd: path_1.dirname(".")
        };

... may be a workable long term solution.

I did a quick test on Windows (the only thing I have access to at the moment) and all seemed to be happy with just that change.

**Comment by kak-tus** [comment]
Thank's. Fixed this issue like your solution. But set cwd path with "." broke support for loading perltidy profile by perltidy from normal filesystem. So I set this only for virtual FS.
Later I will add support for searching for ".perltidyrc" also at virtual FS.
