### ISSUE TITLE
Perltidy erases code instead formatting it 

### ISSUE THREAD

**Issue by antoimau** [kak-tus/perltidy-more#7]
Hello,

I am working under Ubuntu 18.04 and installed perltidy-more into my visual code studio.
When I am selecting a part of code and the ctrl+shift+p and running perltidy, instead of formatting the source code, it erases it.
I tried to disable all the others Perl extension I had but perltidy still behave this way.
It is correctly working under Ubuntu 14.04 though.
I have no clue what could cause this issue. Any ideas ?

Best regards,
Antoimau

**Comment by kak-tus** [comment]
Please, try:
1. Check, that perltidy is installed and working. Something like this
```
$ echo '1' | perltidy 
1
```
2. Get path there is it installed
```
$ whereis perltidy 
perltidy: /usr/bin/perltidy /usr/share/man/man1/perltidy.1p.gz
```
3. And copy this full path to "perltidy-more.executable" parameter in vscode (it has "perltidy" value by default).

**Comment by antoimau** [comment]
Hello,

It works perfectly now !
Thank you for the help.
